// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCc6keiuYKDuzZaGKV-uHzDbUINOANqfVY',
    appId: '1:248784625587:web:385c21f6951b18ef9075c6',
    messagingSenderId: '248784625587',
    projectId: 'etammn-ad1cf',
    authDomain: 'etammn-ad1cf.firebaseapp.com',
    storageBucket: 'etammn-ad1cf.appspot.com',
    measurementId: 'G-6DB46LD0P5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCc6keiuYKDuzZaGKV-uHzDbUINOANqfVY',
    appId: '1:248784625587:android:906afe973fb1fd299075c6',
    messagingSenderId: '248784625587',
    projectId: 'etammn-ad1cf',
    storageBucket: 'etammn-ad1cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPsE57-XDBk5D_E247msNvXqa2cmGNSBg',
    appId: '1:248784625587:ios:a23216ff36439ff99075c6',
    messagingSenderId: '248784625587',
    projectId: 'etammn-ad1cf',
    storageBucket: 'etammn-ad1cf.appspot.com',
    iosClientId: '248784625587-t9q84qf4teon5ejip3u859gd65cpv0f0.apps.googleusercontent.com',
    iosBundleId: 'com.etammn.client',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCc6keiuYKDuzZaGKV-uHzDbUINOANqfVY',
    appId: '1:248784625587:ios:105663dc6109958a9075c6',
    messagingSenderId: '248784625587',
    projectId: 'etammn-ad1cf',
    storageBucket: 'etammn-ad1cf.appspot.com',
    iosClientId: '248784625587-b03utcmuca9gda6s7sk7r700pnmp73fb.apps.googleusercontent.com',
    iosBundleId: 'com.etammn.client.etammnClient.RunnerTests',
  );
}
